# -*- coding: utf-8 -*-
"""Copy of veri_gorsellestirme_temper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IJWe2iuc_HzbZ3HS5eJsAyOx5eNhKA52

## Veri Seti Hikayesi ve Yapısının İncelenmesi
"""

#@title
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
df =pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Temperleme_Denemeler/AK0001C.xlsx', sheet_name="Sayfa2")
#df =pd.read_excel('Temperleme_Denemeler/AK0001C.xlsx', sheet_name="Sayfa2")
df.head()

#@title
df.describe()

"""## Eksik Değerlerin İncelenmesi

## Isıtma, soğutma ve kırılma değikenleri zaman grfiği
"""

#@title
df.plot(figsize=(12, 20), subplots=True)

"""## Kırılmanın "Şoklama Hava Sıcaklığı" na göre dağılımı"""

#@title
f, ax = plt.subplots(figsize=(7, 5))
sns.despine(f)
df=df
sns.histplot(
    df,
    x="Şoklama Hava Sıcaklığı", hue="Kırılma",
    multiple="stack",
    palette="light:m_r",
    edgecolor=".3",
    linewidth=.5,
    log_scale=True,
)
ax.xaxis.set_major_formatter(mpl.ticker.ScalarFormatter())
#ax.set_xticks([15,20,25,30,35,40])

#@title
sns.displot(data=df, x="Şoklama Hava Sıcaklığı", col="Kırılma", kde=True)

"""## Kırılma'nın soğutma hava basınçlarına göre değişimleri

"""

#@title
sns.set_theme(style="white")

g = sns.PairGrid(df, hue="Kırılma", vars=("Şoklama Hava Sıcaklığı","AB1","ÜB1","AB2","ÜB2"), diag_sharey=False)
g.map_diag(sns.histplot)
g.map_offdiag(sns.scatterplot, size=df[("Kırılma")])
g.add_legend()

"""## Kırılma'nın Şoklama Hava Sıcaklığı'na bağlı zamanla değişimi dağılımı"""

#@title
sns.scatterplot(y = "Şoklama Hava Sıcaklığı", x = df.index, hue="Kırılma",size="Kırılma",data = df);

"""## Kırılma'nın Altbasınç ve Üstbasınca göre değişimi"""

#@title

fig, ax = plt.subplots()
fig.set_size_inches(15,5);
sns.scatterplot(y = "AB1", x = "Şoklama Hava Sıcaklığı", hue = "Kırılma",data = df,palette = "coolwarm", ax = ax);
ax2 = ax.twinx()
sns.scatterplot(y = "ÜB1", x = "Şoklama Hava Sıcaklığı", hue = "Kırılma", ax=ax2, data=df,palette = "hot");

"""## Kırolmanın Alt ve Üst basınca göre zamana bağlı değişimi"""

#@title
sns.set_theme(style="ticks")

# Initialize the figure with a logarithmic x axis
f, ax = plt.subplots(figsize=(15, 9))
ax.set_xscale("linear")

# Plot the orbital period with horizontal boxes
sns.boxplot(x="Şoklama Hava Sıcaklığı", y="AB1", data=df,
            whis=[0, 100], width=.6, palette="vlag",ax=ax)
sns.boxplot(x="Şoklama Hava Sıcaklığı", y="ÜB1", data=df,
            whis=[0, 100], width=.6, palette="Set2", ax=ax)
ax2 = ax.twinx()
# Add in points to show each observation
sns.stripplot(x="Şoklama Hava Sıcaklığı", y=df.index,hue="Kırılma", data=df,
              size=5, linewidth=1,ax=ax2)

# Tweak the visual presentation
ax.xaxis.grid(True)
ax.set(ylabel="")
sns.despine(trim=True, left=True)

"""## Doğrusal İlişkinin Gösterilmesi"""

sns.pairplot(df, hue = "Kırılma");

"""## Verinin korelosyon dağılımı"""

#@title
# Let's make our correlation matrix for df
corr_matrix = df.corr()
fig, ax = plt.subplots(figsize=(15, 15), )
#ax.set_xlabel('X Label', fontsize=9)  # set x-axis label font size
#ax.set_ylabel('Y Label', fontsize=9)  # set y-axis label font size
ax.tick_params(axis='x', labelsize=9) # set x-axis tick label font size
ax.tick_params(axis='y', labelsize=9) # set x-axis tick label font size
ax = sns.heatmap(corr_matrix,
                 annot=True,
                 linewidths=0.6,
                 fmt=".2f",
                 cmap="YlGnBu", annot_kws={"size": 7});
bottom, top = ax.get_ylim()
ax.set_ylim(bottom + 0, top - 0)
ax.tick_params(axis='y', labelsize=9) # set x-axis tick label font size